### ISSUE TITLE
DNS-Paket error: type 46 is invalid

### ISSUE THREAD

**Issue by ngrepo** [mschorsch/ipset-dns-rs#1]
ipset-dns-rs[27337]: ERROR: DNS-Paket error: type 46 is invalid

**Comment by mschorsch** [comment]
@Nachtgast Do you have a reproducer?

**Comment by ngrepo** [comment]
I turned off edns in the bind and the error disappeared.

resolver scheme: bind --> ipset-dns-rs --> dnscrypt
